[0m22:54:38.980934 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002012E0C9550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002012DD7C110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002012D95C320>]}
[0m22:54:38.990019 [debug] [MainThread]: An error was encountered while trying to send an event


============================== 22:54:38.990926 | 8135e87e-04cf-4080-8331-349e08086505 ==============================
[0m22:54:38.990926 [info ] [MainThread]: Running with dbt=1.9.5
[0m22:54:38.992922 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\yamin\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init icc_cwc2019', 'send_anonymous_usage_stats': 'True'}
[0m22:54:39.028019 [debug] [MainThread]: Starter project path: C:\Users\yamin\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m22:54:39.066012 [info ] [MainThread]: 
Your new dbt project "icc_cwc2019" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:54:39.068589 [info ] [MainThread]: Setting up your profile.
[0m22:57:43.958633 [info ] [MainThread]: Profile icc_cwc2019 written to C:\Users\yamin\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m22:57:43.962624 [debug] [MainThread]: Command `dbt init` succeeded at 22:57:43.961626 after 185.38 seconds
[0m22:57:43.963625 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002012E069100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002013DF77E30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002012E0C9550>]}
[0m22:57:43.964631 [debug] [MainThread]: An error was encountered while trying to send an event
[0m22:57:43.966612 [debug] [MainThread]: Flushing usage events
[0m23:47:16.481112 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FDA2577290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FDA4C7FEC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FDA4C7FC80>]}
[0m23:47:16.486124 [debug] [MainThread]: An error was encountered while trying to send an event


============================== 23:47:16.487108 | 6438036c-8c1e-4bfa-aa5c-77d7a522fdfa ==============================
[0m23:47:16.487108 [info ] [MainThread]: Running with dbt=1.9.5
[0m23:47:16.488111 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\yamin\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt test', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:47:16.489108 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\yamin\OneDrive\cricket_dataset\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:47:16.490110 [debug] [MainThread]: Command `dbt test` failed at 23:47:16.490110 after 0.19 seconds
[0m23:47:16.490110 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FDA4C7FEC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FDA297CBF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FDA455C5F0>]}
[0m23:47:16.491125 [debug] [MainThread]: An error was encountered while trying to send an event
[0m23:47:16.491125 [debug] [MainThread]: Flushing usage events
